### PR TITLE
array.ctor implementation

### LINKED ISSUE #221: implement array.ctor to create array objects
`array` constructor implementation is missing. Now we cannot create arrays without a special wrapping object, like here:
```
[elements...] > wrapper
  elements > @
```
Here, the `wrapper` object is used to implement the constructor behavior.

### PR DESCRIPTION
**Pull request by nlchar**
Fixes #221

### CODE REVIEW

**Comment by nlchar** [comment]
@yegor256 your help is much needed.
I want to implement a constructor for `array`.  
For now, I do it like this:  
```
[elements...] > array
  elements > @

  # Obtain the length of the array.
  [] > length /int

  # Take one element from the array, at the
  # given position.
  [i] > get /object
```
And I get this error:  
```
<testcase name="testRealCompilation" classname="org.eolang.maven.CompileMojoTest" time="1.442">
    <error type="java.lang.IllegalStateException"><![CDATA[java.lang.IllegalStateException: There are 1 errors in code.eo, see log above at org.eolang.maven.CompileMojo.noErrors(CompileMojo.java:215)
```  
This is because the parser puts all the `array`'s attributes 'inside' each attribute:
```
<objects>
      <o line="3" name="array" original-name="array">
         <o line="3" name="elements" vararg=""/>
         <o atom="int"
            base="array$length"
            cut="1"
            line="4"
            name="length"
            ref="4">
            <o as="elements" base="elements" level="1" ref="3"/>
            <o as="get" base="get" level="1" ref="7"/>
            <o as="append" base="append" level="1" ref="11"/>
            <o as="reduce" base="reduce" level="1" ref="15"/>
            <o as="mapi" base="mapi" level="1" ref="18"/>
            <o as="map" base="map" level="1" ref="24"/>
            <o as="@" base="@" level="1" ref="32"/>
         </o>
         <o atom="object"
            base="array$get"
            cut="2"
            line="7"
            name="get"
            ref="7">
            <o as="elements" base="elements" level="1" ref="3"/>
            <o as="length" base="length" level="1" ref="4"/>
            <o as="append" base="append" level="1" ref="11"/>
            <o as="reduce" base="reduce" level="1" ref="15"/>
            <o as="mapi" base="mapi" level="1" ref="18"/>
            <o as="map" base="map" level="1" ref="24"/>
            <o as="@" base="@" level="1" ref="32"/>
         </o>
         <o atom="array"
            base="array$append"
            cut="4"
            line="11"
            name="append"
            ref="11">
            <o as="elements" base="elements" level="1" ref="3"/>
            <o as="length" base="length" level="1" ref="4"/>
            <o as="get" base="get" level="1" ref="7"/>
            <o as="reduce" base="reduce" level="1" ref="15"/>
            <o as="mapi" base="mapi" level="1" ref="18"/>
            <o as="map" base="map" level="1" ref="24"/>
            <o as="@" base="@" level="1" ref="32"/>
         </o>
```
How can we omit this check or put the varang attribute at the end of the list passed to each of attributes? 
And also why do we pass all the attributes inside each of them?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#222](https://github.com/cqfn/eo/issues/222); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@nlchar I don't think it's a good idea in the first place... what you are doing looks weird. I think we should introduce a syntax for array making:

```
{ x 5 3.14 "Hello" } > a
```

or vertical one:

```
{ > a
  x 
  5 
  3.14 
  "Hello" 
}
```

**Comment by nlchar** [comment]
> @nlchar I don't think it's a good idea in the first place... what you are doing looks weird. I think we should introduce a syntax for array making:
> 
> ```
> * x 5 3.14 "Hello" > a
> ```
> 
> or vertical one:
> 
> ```
> * > a
>   x 
>   5 3.14 
>   "Hello" 
> ```
> 
> or without naming:
> 
> ```
> * x 5 3.14 "Hello"
> *
>   x 
>   5 3.14 
>   "Hello" 
> ```

@yegor256 if `NAME` may be any UNICODE char (see #204), then this is rather an object-level sugar:
`array.eo`:
```
[elements...] > *
  elements > @ 

[] > array
...tldr;
``` 
What do you think?

**Comment by yegor256** [comment]
@nlchar I think you were right in the first place. Let's go with your original design (`elements...`). I fixed the bug that prevented you from doing this: #237

**Comment by nlchar** [comment]
I failed with the task in the previous sprint, so I moved it to the current sprint.

**Comment by nlchar** [comment]
@yegor256 all the array tests fail. 
The empty array length test fails with the following error:
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.009 s <<< FAILURE! - in org.eolang.EOemptyArrayLengthTestTest
[ERROR] org.eolang.EOemptyArrayLengthTestTest.testWorks  Time elapsed: 0.002 s  <<< ERROR!
java.lang.ClassCastException: Cannot cast org.eolang.phi.PhEta to org.eolang.phi.Data
```
It is understandable. However, other tests fail with this error: 
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.043 s <<< FAILURE! - in org.eolang.EOnonEmptyArrayLengthTestTest
[ERROR] org.eolang.EOnonEmptyArrayLengthTestTest.testWorks  Time elapsed: 0.004 s  <<< ERROR!
java.lang.IllegalStateException: You can't overwrite λO
```
What source the error might have? Does it fail because of the recurrent nature of the proposed solution? I mean, the `elements...` free attribute is also an `array` object, so it might (I am not sure exactly) result in the `cannot override lambda exception`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#222](https://github.com/cqfn/eo/issues/222); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@nlchar I'm not sure. But maybe we should go with the syntax I proposed? Using the `*`

**Comment by nlchar** [comment]
Implemented in #276 by Yegor.
The PR is closed since it is not relevant.

**Comment by 0crat** [comment]
Code review was too long (15 days), architects (@yegor256) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
Pull request [#222](https://github.com/cqfn/eo/issues/222) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
