### PR TITLE
useful attributes for float object are implemented & covered

### LINKED ISSUE #224: [enhancement] implement float.mul
`float.mul` should datarize to the production of its base `float` object and its `x` free attribute.

### LINKED ISSUE #226: [enhancement] implement float.add
`float.add` should datarize to the sum of its base `float` object and its `x` free attribute

### LINKED ISSUE #229: [enhancement] implement float.neg
`float.neg` should datarize to the negate value of its base `float` object

### LINKED ISSUE #230: [enhancement] implement float.sub
`float.sub` should datarize to the difference between its base `float` object and its `x` free attribute

### LINKED ISSUE #232: [enhancement] implement float.div
`float.div` should datarize to the quotient of the division of its base `float` object by its `x` free attribute

### LINKED ISSUE #233: [enhancement] implement float.pow
`float.pow` should datarize to its base `float` object raised to the power of its `x` free attribute

### PR DESCRIPTION
**Pull request by nlchar**
Fixes #224  
Fixes #226 
Fixes #229
Fixes #230 
Fixes #232 
Fixes #233

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#228](https://github.com/cqfn/eo/issues/228); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by nlchar** [comment]
@yegor256 ready to merge
I used one PR for many issues since issues are interdependent

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#228` is not assigned, can't get performer

**Pull request merged**
