### PR TITLE
Introduced sin and cos in runtime

### PR DESCRIPTION
**Pull request by maxonfjvipon**

### CODE REVIEW

**Comment by yegor256** [comment]
@maxonfjvipon I think it would be better to have `float.cos` and `float.sin` instead of `cos` and `sin` standalone objects.

**Comment by maxonfjvipon** [comment]
@yegor256 please check this out. If it's good I would continue to add more objects like these. 
Also I wanted to ask about these objects written in `eo`: should I make a PR at this repository or at [objectionary](https://github.com/yegor256/objectionary)?

**Comment by yegor256** [comment]
@maxonfjvipon all looks good now, but you also should add these two "methods" to `float.eo` file. Otherwise, they won't be visible by EO compiler. No need to touch "objectionary": your objects will appear there automatically, once we release a new version of this repository to Maven Central.

**Comment by yegor256** [comment]
@maxonfjvipon also, would be nice if you would add some tests to `float-tests.eo`.

**Comment by maxonfjvipon** [comment]
@yegor256 Ok. Will be done soon

**Comment by yegor256** [comment]
@maxonfjvipon if you think that the PR is ready for merging, say so explicitly by posting a new message. Otherwise, it will hang in there forever :)

**Comment by maxonfjvipon** [comment]
@yegor256 Oh, my bad) I think the PR is ready to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@maxonfjvipon thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#598` is not assigned, can't get performer

**Pull request merged**
