### PR TITLE
implemented char object with .toString attr + tests

### LINKED ISSUE #191: [bug] Missing implementation for the char data type
The compiler recognized these data-types, however, the eo-runtime does not have the corresponding objects for them. Hence, the following errors are produced on compilation.
And for `char`:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project quick-start: Compilation failure: Compilation failure: 
[ERROR] /home/nlchar/sandbox/target/generated-sources/eo/EOapp.java:[30,39] cannot find symbol
[ERROR]   symbol:   class EOchar
[ERROR]   location: package org.eolang
[ERROR] /home/nlchar/sandbox/target/generated-sources/eo/EOapp.java:[32,68] cannot find symbol
[ERROR]   symbol:   variable a
[ERROR]   location: class sandbox.EOapp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
***The syntax for `char`:***

CHAR
  
**EBNF:**
```EBNF
CHAR     ::= "'" [0-9a-zA-Z] "'"
```

### PR DESCRIPTION
**Pull request by nlchar**
Fixes #191

### CODE REVIEW

**Comment by nlchar** [comment]
@yegor256 your help is needed.
Please, have a look at `char.eo` and `char-tests.eo`.
When running the test, I get this error:
```
[ERROR] org.eolang.EOcharToStringTest.testWorks  Time elapsed: 0.021 s  <<< ERROR!
org.eolang.phi.Attr$Exception: Error at org.eolang.EOstring$EOeq#φ
        at org.eolang.phi.AtNamed.get(AtNamed.java:66)
        at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
        at org.eolang.phi.Data$Take.take(Data.java:125)
        at org.eolang.phi.Data$Take.take(Data.java:130)
        at org.eolang.EOcharToStringTest.testWorks(EOcharToStringTest.java:40)

Caused by: org.eolang.phi.Attr$Exception: Error at org.eolang.txt.EOsprintf#φ
        at org.eolang.phi.AtNamed.get(AtNamed.java:66)
        at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.Data$Take.take(Data.java:125)
        at org.eolang.phi.Data$Take.take(Data.java:130)
        at org.eolang.EOstring$EOeq.lambda$new$0(EOstring$EOeq.java:46)
        at org.eolang.phi.AtLambda.lambda$copy$1(AtLambda.java:58)
        at org.eolang.phi.AtLambda.get(AtLambda.java:63)
        at org.eolang.phi.AtBound.get(AtBound.java:56)
        at org.eolang.phi.AtNamed.get(AtNamed.java:63)
        ... 73 more
Caused by: org.eolang.phi.Attr$Exception: Error at org.eolang.phi.Data.Value#data
        at org.eolang.phi.AtNamed.get(AtNamed.java:66)
        at org.eolang.phi.Data$Take.take(Data.java:125)
        at org.eolang.txt.EOsprintf.lambda$new$0(EOsprintf.java:57)
        at org.eolang.phi.AtLambda.lambda$copy$1(AtLambda.java:58)
        at org.eolang.phi.AtLambda.get(AtLambda.java:63)
        at org.eolang.phi.AtBound.get(AtBound.java:56)
        at org.eolang.phi.AtNamed.get(AtNamed.java:63)
        ... 87 more
Caused by: org.eolang.phi.Attr$Exception: Can't get(), attribute "data" is absent
        at org.eolang.phi.AtAbsent.get(AtAbsent.java:58)
        at org.eolang.phi.AtNamed.get(AtNamed.java:63)
        ... 93 more

```
I think that the error is caused by the code produced by the compiler for the case then we need to reference `data` attribute of the parent object inside the attribute object. 
The `char.toString` attribute is compiled into this:
```java

/*
 * This file was auto-generated by eolang-maven-plugin
 * on 2021-02-06T23:29:17.413+03:00. Don't edit it,
 * your changes will be discarded on the next build.
 * The sources were compiled to XML on
 * 2021-02-06T20:28:51.779589Z by the EO compiler v.1.0-SNAPSHOT.
 */

package org.eolang;

import org.eolang.*;
import org.eolang.phi.*;

public final class EOchar$EOtoString extends PhDefault {
  public EOchar$EOtoString() {
    this(new PhEta());
  }
  public EOchar$EOtoString(final Phi parent) {
    super(parent);
    this.add("φ", new AtBound(new AtOnce(new AtLambda(this, self -> {
      Phi ret = new org.eolang.txt.EOsprintf(self);
      ret = new PhCopy(ret);
        Phi ret_1 = new org.eolang.EOstring(self);
        ret_1 = new PhCopy(ret_1);
          ret_1 = new PhWith(ret_1, "data", new Data.Value<String>("%c"));
        Phi ret_2 = new PhMethod(new PhMethod(self, "ρ"), "data"); // <------ HERE
        ret = new PhWith(ret, 0, ret_1);
        ret = new PhWith(ret, 1, ret_2);
      return ret;
    }))));
  }
}

```
This line looks quite strange. Should it work? 
```java
Phi ret_2 = new PhMethod(new PhMethod(self, "ρ"), "data"); // <------ HERE
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#206](https://github.com/cqfn/eo/issues/206); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@nlchar I suggest replacing this

```
sprintf "%c" data > @
```

with this

```
sprintf "%c" $ > @
```

**Comment by yegor256** [comment]
@nlchar hold on, I'm not sure this feature is implemented yet. We never tried it before: to use attributes from parent objects. I think we need a new syntax for that. Something like this:

```
sprintf "%c" ^.data > @
```

**Comment by nlchar** [comment]
> @nlchar I suggest replacing this
> 
> ```
> sprintf "%c" data > @
> ```
> 
> with this
> 
> ```
> sprintf "%c" $ > @
> ```

I tried it before. It does not work as well, but with a different error (Phi cannot be cast to Data).

**Comment by yegor256** [comment]
@nlchar yes, indeed, nothing will work. We have to implement new syntax with `^` to refer to the parent object.

**Comment by yegor256** [comment]
@nlchar will you do it, or you want me to help?

**Comment by nlchar** [comment]
> @nlchar will you do it, or you want me to help?

@yegor256 your instructions would help us. We still don't know quite well how the entire process of translation from EO to Java works.

**Comment by yegor256** [comment]
@nlchar I'll try in #211

**Comment by yegor256** [comment]
@nlchar I believe it's fixed in #211 Try master branch and use this code:

```
+package org.eolang
+alias sprintf org.eolang.txt.sprintf

[] > char
  # Converts char to string
  [] > toString
    sprintf "%c" $ > @
```

**Comment by nlchar** [comment]
@yegor256 ready for review

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@nlchar thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#206` is not assigned, can't get performer

**Pull request merged**
