### PR TITLE
A new transcompilation model of EO programs to Java sources with more readable and better performing target Java code

### PR DESCRIPTION
**Pull request by hadiSaleh**
A new transcompilation model of EO programs to Java sources with more readable and better performing target Java code

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#300](https://github.com/cqfn/eo/issues/300); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@hadiSaleh many thanks for the contribution, but this is too much for a single PR :(

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#300` is not assigned, can't get performer

**Comment by 0crat** [comment]
Pull request [#300](https://github.com/cqfn/eo/issues/300) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
