### PR TITLE
mapi and map array mutation issue fixed and covered by test

### LINKED ISSUE #195: [bug] Wrong array.mapi and array.map implementation
The implementation of `array.mapi` misses `.copy` method call. Because of it the `array` becomes mutable. Because of it `mapi` and `map` attribute objects are unsafe and cannot be used at all (because EO runtime evaluates the `array` multiple times and on the second iteration the objects are already mapped and do not contain the attributes the objects previously had).
```JAVA
/**
 * MAPI.
 *
 * @since 1.0
 */
public class EOarray$EOmapi extends PhDefault {

    public EOarray$EOmapi(final Phi parent) {
        super(parent);
        this.add("f", new AtFree());
        this.add("φ", new AtBound(new AtLambda(this, self -> {
            final Phi[] array = new Data.Take(
                self.attr("ρ").get() /* HERE */
            ).take(Phi[].class);
            for (int idx = 0; idx < array.length; ++idx) {
                final Phi after = self.attr("f").get().copy();
                after.attr(0).put(array[idx]);
                after.attr(1).put(new Data.Value<>(idx));
                array[idx] = after;
            }
            return new Data.ToPhi(array);
        })));
    }

}

```
Hence, this example cannot be run:
```
+package sandbox
+alias sprintf org.eolang.txt.sprintf
+alias stdout org.eolang.io.stdout

[args...] > app
  map. > squares!
    args
    [current]
      pow. > @
        current.toInt
        2

  stdout > @
    sprintf
      "%d\n"
      reduce.
        squares
        0
        [accumulator current]
          accumulator.add current > @

```

### PR DESCRIPTION
**Pull request by nlchar**
Fixes #195 
@yegor256 please, check if everything is correct regarding implementation & testing.

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@nlchar I think you should sync your branch with master

**Comment by nlchar** [comment]
@yegor256 done. I hope this would help to merge the pr into the base repository.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
