### PR TITLE
Dockerize sandbox

### PR DESCRIPTION
**Pull request by Sitiritis**
Hello!

I am sending this PR in order to facilitate usage of the sandbox, so that people who don't have maven and/or JRE installed locally can still compile and run EO programs in docker.

If there is something wrong with PR, please let me know, I will fix it.

### CODE REVIEW

**Comment by yegor256** [comment]
@Sitiritis I suggest we simplify the instructions. Now they look too long with too many options for the user. Let's omit most of the options, like changing the Maven command -- almost nobody will need this.

**Comment by Sitiritis** [comment]
@yegor256 I agree that the instruction looks long now, nevertheless I would still like to leave both options, since there might be people who, for some reasons, don't have docker installed and cannot install it. It would be nice to have instruction for both cases, so people are free to chose how they want to run programs in the sandbox and have different option, in case other is not working or produce strange results.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#284` is not assigned, can't get performer

**Pull request merged**
