### PR TITLE
Float Parsing Bug Fix

### LINKED ISSUE #186: [bug] Wrong float constants parsing
`float` constant parsing is performed wrong.  
```
+package sandbox
+alias sprintf org.eolang.txt.sprintf
+alias stdout org.eolang.io.stdout

[args...] > app
  stdout > @
    sprintf
      "%%.9f\n"
      9999999999.0000012

```
Here, the `9999999999.0000012` is parsed as `1.0E10`:
**target/parse/app.eo.xml**
```xml

<objects>
    <o line="5" name="app">
       <o line="5" name="args" vararg=""/>
       <o base="stdout" line="6" name="@">
          <o base="sprintf" line="7">
             <o base="string" data="string" line="8">%%.9f\n</o>
             <o base="float" data="float" line="9">1.0E10</o>
          </o>
       </o>
    </o>
</objects>
```

### PR DESCRIPTION
**Pull request by nlchar**
Fixes #186 

Accidentally removed the branch. Now, it is recovered.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#218](https://github.com/cqfn/eo/issues/218); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by nlchar** [comment]
@yegor256 ready for review & merge.
you previously reviewed the PR, but I accidentally deleted the branch. Now, I revoked it again.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#218` is not assigned, can't get performer

**Pull request merged**
