### PR TITLE
new dependency model for the hse transcompiler

### PR DESCRIPTION
**Pull request by nlchar**

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@nlchar thanks! very good code!

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#321` is not assigned, can't get performer

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.1`

**Pull request merged**
