### PR TITLE
Add BYTE type

### PR DESCRIPTION
**Pull request by andreoss**
Per #533 

- Add byte type

### CODE REVIEW

**Comment by yegor256** [comment]
@andreoss how will this object be accessible from `.eo` syntax?

**Comment by andreoss** [comment]
@yegor256 There is no special syntax, but `char` can be converted to `byte`.
The plan is to use this object to implement `bytes.as-array`, or make `bytes` and array of `byte` with inheritance.

**Comment by yegor256** [comment]
@andreoss we should be very careful with new objects of basic level. Are you sure we can't use `bytes` with a single byte inside? We really need a special new one `byte`?

**Comment by andreoss** [comment]
@yegor256 What is the issue with adding new objects? Won't  all primitive types eventually be mapped to Eo?
`bytes` is to cumbersome to use, because it lacks `array`'s methods, like `append` and `reduce`.
For example, we could re-implement `string.trim`  and other methods in Eo, but there is no path from `string` to `array` of either `byte` or `char`.
Also `int.eo` and `float.eo` are almost identical, if we had  a base object like `PhPrimitive`, adding a new type like a `byte` would be trivial

**Comment by andreoss** [comment]
@yegor256 Are you sure `BYTE` is not necessary? If so, please close this, I will continue to work #540 without `byte` type

**Comment by yegor256** [comment]
@andreoss yes, I think it's not necessary. We already have `bytes`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#540](https://github.com/cqfn/eo/issues/540); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#540](https://github.com/cqfn/eo/issues/540); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Pull request [#540](https://github.com/cqfn/eo/issues/540) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
