### PR TITLE
fixed bool.and & bool.or short-circuiting bug

### LINKED ISSUE #235: [bug] wrong short-circuiting implementation in bool.and & bool.or
The current implementation of short-circuiting in `bool.and` and `bool.or` is wrong. It should consider the `ρ` object first, not its application to the first element of the `x` vararg.  
This makes the datarization process of the `bool.and` and `bool.or` less efficient and conceptually wrong.

### PR DESCRIPTION
**Pull request by nlchar**
Fixes #235

### CODE REVIEW

**Comment by nlchar** [comment]
@yegor256 ready for review

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#236](https://github.com/cqfn/eo/issues/236); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#236` is not assigned, can't get performer

**Pull request merged**
