### PR TITLE
memory dataization bug fix

### LINKED ISSUE #248: Decoration mechanism does not work with memory
Here is an example of a program that uses the decoration mechanism together with a `memory` object:  
```
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[a] > test
  a > @
  "string" > attr1
  123 > attr2


[] > app
  memory > m
  seq > @
    m.write (test 101)
    stdout
      sprintf
        "%s %s %s"
        m
        m.attr1
        m.attr2

```
It fails with the following error:  
```
Caused by: org.eolang.phi.Attr$Exception: Error at org.eolang.EOint#attr1
        at org.eolang.phi.AtNamed.get(AtNamed.java:66)
        at org.eolang.phi.PhDefault$AtChild.get(PhDefault.java:178)
        at org.eolang.phi.PhMethod.lambda$new$0(PhMethod.java:41)
        at org.eolang.phi.Data$Once.take(Data.java:58)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.Data$Take.take(Data.java:122)
        at org.eolang.txt.EOsprintf.lambda$new$0(EOsprintf.java:57)
        at org.eolang.phi.AtLambda.lambda$copy$1(AtLambda.java:58)
        at org.eolang.phi.AtLambda.get(AtLambda.java:63)
        at org.eolang.phi.AtBound.get(AtBound.java:56)
        at org.eolang.phi.AtNamed.get(AtNamed.java:63)
        ... 31 more
Caused by: org.eolang.phi.Attr$Exception: Can't get(), attribute "attr1" is absent
        at org.eolang.phi.AtAbsent.get(AtAbsent.java:58)
        at org.eolang.phi.AtNamed.get(AtNamed.java:63)
        ... 41 more
```
However, if we omit the `memory` object like this:  
```
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[a] > test
  a > @
  "string" > attr1
  123 > attr2


[] > app
  test 122 > m
  stdout > @
    sprintf
      "%s %s %s"
      m
      m.attr1
      m.attr2

```
The program works fine:  
```
122 string 123
```

### PR DESCRIPTION
**Pull request by nlchar**
May fix #248

### CODE REVIEW

**Comment by 0crat** [comment]
@nlchar[/z](https://www.0crat.com/u/nlchar) this pull request is too small, just 3 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by nlchar** [comment]
@yegor256 is #248 really a bug or is it a feature? My bugfix ruins tests, so it seems like the `memory` object may need to stay datarize-first. However, the language design should accept only lazy datarization. Otherwise, no real decoration may be used with the object inside the `memory` (see #248).
What do you think?

**Comment by yegor256** [comment]
@nlchar it's hard to tell what's wrong without a test first. Maybe you can create a test, which would reproduce a problem, push it to this PR and then we discuss the fix.

**Comment by yegor256** [comment]
@nlchar I guess we can close this one?

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#251` is not assigned, can't get performer

**Pull request closed without merging**
