### PR TITLE
array.length

### LINKED ISSUE #219: [enhancement] array.length
Implement `array.length` that obtains the length of the base `array` object

### PR DESCRIPTION
**Pull request by nlchar**
Fixes #219

### CODE REVIEW

**Comment by nlchar** [comment]
@yegor256 ready for review & merge

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#220](https://github.com/cqfn/eo/issues/220); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#220` is not assigned, can't get performer

**Pull request merged**
