### PR TITLE
test(eo-maven-plugin): enable SnippetTest on Windows

### PR DESCRIPTION
**Pull request by baudoliver7**
After enabling `SnippetTest` on Windows, we realized that the project relied completely on the encoding of the system during `xsl` transformations, which made the success of build random from one system to another.

We also noticed that `Process` used in `SnippetTest` to build java files was also relying on the encoding of the system while parsing command to the process before running, which made special characters unreadable for some charsets.

We fixed them all and introduced another `todo` to fix `PlaceTest` and `UnplaceTest` for Windows.

Close: #526

### CODE REVIEW

**Comment by yegor256** [comment]
@baudoliver7 they don't pass: https://github.com/cqfn/eo/runs/4625518195?check_suite_focus=true

**Comment by baudoliver7** [comment]
@yegor256 I haven't finish yet :)

**Comment by baudoliver7** [comment]
@yegor256 all things are now good here. Builds fail because of #545.
Please, let me investigate on that.

**Comment by yegor256** [comment]
@baudoliver7 try to run `xcop` with your branch, you will see how it complains

**Comment by baudoliver7** [comment]
@yegor256 After running `xcop` on my branch, it shows me nothing.
```console
baudoliver7@MBP-de-Olivier eo % git status
Sur la branche 526_enable_test_windows
Votre branche est `a jour avec 'origin/526_enable_test_windows'.

rien `a valider, la copie de travail est propre
baudoliver7@MBP-de-Olivier eo % xcop
baudoliver7@MBP-de-Olivier eo % 
```

**Comment by baudoliver7** [comment]
@yegor256 I added `xcop` to `ci`. `xcop` checks passed.

**Comment by yegor256** [comment]
@rultor merge

**Comment by baudoliver7** [comment]
@yegor256 It is a bug related to `rultor`. I suggest you to merge directly for this time :)

**Comment by baudoliver7** [comment]
@yegor256 I will wait the end of `tojos release v0.8.2` building to add it as dependency here.

**Comment by yegor256** [comment]
@baudoliver7 adding executable binary files to Git repo is a very very bad idea

**Comment by baudoliver7** [comment]
@yegor256 Ok. I need `xargs` support on windows and I got zip file somewhere. What do you suggest to me ?

**Comment by yegor256** [comment]
@baudoliver7 it's better to rely on tools provided by Windows out of the box

**Comment by baudoliver7** [comment]
Ok. Another question, could I change special characters `α` and `τ` (from file `eo-parser/src/main/resources/org/eolang/parser/optimize/abstracts-float-up.xsl`) by `a` and `t` ?

**Comment by baudoliver7** [comment]
@yegor256 please, check/merge. Looks good now.

**Comment by baudoliver7** [comment]
@yegor256 please, check/merge. Looks good now.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
