### PR TITLE
Fixed Build for Windows

### PR DESCRIPTION
**Pull request by nikololiahim**
This should fix the build for Windows #312 (at least, it did it for me).

### CODE REVIEW

**Comment by 0crat** [comment]
@nikololiahim[/z](https://www.0crat.com/u/nikololiahim) this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@nikololiahim thanks!!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#313` is not assigned, can't get performer

**Pull request merged**
