### PR TITLE
#471 - Check for unused aliases

### PR DESCRIPTION
**Pull request by andreoss**
Per #471 

- Add XSL check for unused alias

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#487](https://github.com/cqfn/eo/issues/487); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@andreoss you need `xcop` installed)

**Comment by andreoss** [comment]
@yegor256 Should be fine now

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@andreoss oops)

**Comment by andreoss** [comment]
@yegor256 Fixed.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@andreoss thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#487` is not assigned, can't get performer

**Pull request merged**
