### PR TITLE
Feature/#296 include maven wrapper

### LINKED ISSUE #296: Include Maven wrapper
The `Readme.md` tells that the project requires Maven to build it. The fact is that not all developers use Maven. And even if they do, not everyone has the specific version installed.

It would be much more convenient if the project provided the [Maven Wrapper](https://maven.apache.org/plugins/maven-wrapper-plugin/wrapper-mojo.html) as a build tool. Firstly, if Maven version required an upgrade, this could be done transparently without bothering contributors. Secondly, this would make the environment easy to reproduce on any machine.

### PR DESCRIPTION
**Pull request by SimonHarmonicMinor**
Resolves #296 

Added Maven Wrapper `3.3.3`

### CODE REVIEW

**Comment by yegor256** [comment]
@SimonHarmonicMinor are you sure it's a good idea to copy-paste Apache code to our repository? Looks a bit wrong to me... I'm not sure how it should be done though.

**Comment by SimonHarmonicMinor** [comment]
@yegor256 this code is actually auto-generated. I used `mvn -N io.takari:maven:wrapper -Dmaven=3.5.2` to create maven wrapper. I'm not sure about licences problems, but the [plugin repository](https://github.com/takari/maven-wrapper) tells that it's under `Apache-2.0 License`. I don't if it is acceptable with the project.

**Comment by yegor256** [comment]
@SimonHarmonicMinor well, if the code auto-generated, it's a bad practice to keep it in Git, I believe. This is what Maven team recommends doing -- committing this to Git?

**Comment by SimonHarmonicMinor** [comment]
@yegor256 ok, I got it now. According to [this page](https://maven.apache.org/plugins/maven-wrapper-plugin/usage.html) there are several ways to include maven wrapper in the project. For instance, one can add either `maven-wrapper.jar` itself or `MavenWrapperDownloader.java` that wil download the artifact. But since `mvnw` and `mvnw.cmd` scripts are already present they will do the job

**Comment by yegor256** [comment]
@SimonHarmonicMinor I'm still very skeptical about us having such a long piece of code copied from somewhere else. Is it possible to import it somehow in runtime?

**Comment by SimonHarmonicMinor** [comment]
@yegor256 not sure about importing it. As I far I understand that's a common approach in the software development. For example, here is the [spring boot project](https://github.com/spring-projects/spring-boot) that uses the same pattern (55.8K stars).
Well, techinally it uses Gradle (`gradlew`) instead of Maven but the idea is the same.

**Comment by SimonHarmonicMinor** [comment]
@yegor256 and here is [another one](https://github.com/hibernate/hibernate-search) with Maven Wrapper (386 stars). It's not so popular as Spring, but still well known

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#298](https://github.com/cqfn/eo/issues/298); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#298](https://github.com/cqfn/eo/issues/298); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#298](https://github.com/cqfn/eo/issues/298); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#298](https://github.com/cqfn/eo/issues/298); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#298](https://github.com/cqfn/eo/issues/298); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#298](https://github.com/cqfn/eo/issues/298); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#298](https://github.com/cqfn/eo/issues/298); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@SimonHarmonicMinor thanks!

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#298` is not assigned, can't get performer

**Pull request merged**
