### PR TITLE
fix: bug when calling an eo with varargs as free attribute

### LINKED ISSUE #534: EODataizeAppCallsVarargsFuncTest.java:46-50: Fix bug EO...
The puzzle `414-78631059` from #414 has to be resolved: 

https://github.com/cqfn/eo/blob/2c0047c25774494530df2a2067d5a58acbd29e19/eo-runtime/src/test/java/EOorg/EOeolang/EODataizeAppCallsVarargsFuncTest.java#L46-L50

The puzzle was created by @baudoliver7 on 23-Dec-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by baudoliver7**
To avoid issue `You can't overwrite X`, we found that vararg attributes have to be transpiled in Java as array of values. What requires solving a major problem : how to know that an abstract object have a vararg attribute ?

To solve the problem, we divided it into 2 parts :
- Local objects (objects defined in the same eo file)
- External objects (objects defined in another eo file)

### Local objects
Local objects are easy to solve given that they are already defined in the same file. So, we introduced a XSL file called [called-objects.xsl](https://github.com/baudoliver7/eo/blob/15e141f30126918310a14bd39fb384a49dd22bbe/eo-maven-plugin/src/main/resources/org/eolang/maven/pre/called-objects.xsl#L80) where we identify (among called object arguments) vararg arguments and transform them to array.

### External objects
The difficulty for external objects is that sources are not available in eo file. To solve this problem, we introduced a file called `eo-header-registry.xml` where we register all headers of eo objects treated in this format :
```xml
<?xml version="1.0" encoding="UTF-8"?>
<headers>
   <header alias="sandbox.fibonacci" name="fibonacci">
      <free-attr name="n"/>
      <free-attr name="small"/>
      <free-attr name="rec"/>
   </header>
   <header alias="sandbox.app" name="app">
      <free-attr name="n"/>
      <free-attr name="f"/>
   </header>
   <header alias="sandbox.small" name="small">
      <free-attr name="n"/>
      <free-attr name="args" vararg=""/>
   </header>
   <header alias="org.eolang.error" name="error">
      <free-attr name="msg"/>
   </header>
</headers>
```
We have chosen to collect these headers just after `Optimize` phase.
When we are ready to transpile (`Transpile` phase), we add at the end of each `xmir` file all headers that the file depends on in the section called `headers` like below :
```xml  
...
   </objects>
   <headers>
      <header alias="sandbox.small" name="small">
         <free-attr name="n"/>
         <free-attr name="args" vararg=""/>
      </header>
      <header alias="sandbox.app" name="app">
         <free-attr name="n"/>
         <free-attr name="f"/>
      </header>
   </headers>
</program>
```
We have chosen to do it at this moment because we are sure that all objects needed are available at this step (see the [section of this blog](https://www.yegor256.com/2021/10/21/objectionary.html#transpile-)).
Then, we introduced before all steps of `Transpile` phase, the XSL transformation by the file `called-object.xsl` which we talked about previously and where we also support resolving varargs for external objects.

### Summary of actions performed
- make available source headers of external objects by creating an EO header registry file
- transform varargs to unvaring array while calling both local and external objects
- introduce tests for new features
- fix broken tests
- enable java and eo tests related to this bug

Fixes #534

### CODE REVIEW

**Comment by baudoliver7** [comment]
@yegor256 we can discuss now :)

**Comment by andreoss** [comment]
@baudoliver7 I looked into it too briefly, there is a simpler solution possibly
1) keep track of arity
2) always treat extra args as varags, here it seems we would need to introduce a new special attribute like phi for all unused/unnamed arguments

Atom can handle only one vararg at it should go last, 
so `foo a (* 1 2 3)` and `foo a 1 2 3` will end up being the same generated code.

**Comment by baudoliver7** [comment]
> @baudoliver7 I looked into it too briefly, there is a simpler solution possibly
> 
> 1. keep track of arity
> 2. always treat extra args as varags, here it seems we would need to introduce a new special attribute like phi for all unused/unnamed arguments
> 
> Atom can handle only one vararg at it should go last, so `foo a (* 1 2 3)` and `foo a 1 2 3` will end up being the same generated code.

@andreoss Thank you for your suggestion !
But after having analyzed, I noticed that simply keep track of arity is not enough (however, it supports my idea of collecting information about free attributes of an abstract object during the process.). It only works when the number of arguments provided is greater than those declared. I think we need to know if the last argument is a vararg for it to work.
For example (let's do it your way), we have this object :
```eo
[n args...] > f
  args.get 0 > @
```
And we do this :
```eo
f 1 2 > a
```
By simply keeping track of arity, we will detect that arguments `1` and `2` are simple integer data. Further, by executing `args.get 0 > @`, we will try to get the first value of the second argument i.e integer `2` which will end up to an error.

**Comment by andreoss** [comment]
@baudoliver7 I still think having arity would be enough, if you always have implicit `vararg` argument.
`[a args..] > foo` - arity = 1 (vararg is not counted), all arguments but the first go to `vararg` attribute
`foo 1 2 3 4` - the first is consumed as `a`, the rest treated as `(* 2 3 4)` and consumed as `vararg`.
And with a XSLT check it will be possible to find extraneous arguments

**Comment by baudoliver7** [comment]
@andreoss About treating vararg as array, I'm completely agree with you. That's what I do by this `xsl:template` [here](https://github.com/baudoliver7/eo/blob/15e141f30126918310a14bd39fb384a49dd22bbe/eo-maven-plugin/src/main/resources/org/eolang/maven/pre/called-objects.xsl#L27).

**Comment by baudoliver7** [comment]
@andreoss The challenge here is to know what are free attributes of external objects referenced in an EO file like I discussed with @yegor256 in the ticket #534. Local objects are easy to solve and don't need all the process you see in my PR.

**Comment by baudoliver7** [comment]
@yegor256 After exchanges with @andreoss, I thought it was worth explaining my solution for better understanding. I did it in PR description.

**Comment by baudoliver7** [comment]
@yegor256 After exchanges with @andreoss, I thought it was worth explaining my solution for better understanding. I did it in PR description.

**Comment by baudoliver7** [comment]
@yegor256 I close this PR to split it in many small ones (in XDSD spirit) to make your code review easier. I remember that my goal with this PR was simply to prove you that what I had proposed works well.

**Pull request closed without merging**
