### PR TITLE
Remove Java code from Grammar

### PR DESCRIPTION
**Pull request by andreoss**
Per #390 

- Remove Java code from Grammar

In attempt to flatten the grammar, similar to this example (https://github.com/antlr/grammars-v4/blob/master/python/tiny-python/tiny-grammar-without-actions/Python3.g4).
At the end the grammar will not have only mentions of TAB or UNTAB, thus making `htail` and `tail` unnecessary.

Note: this change is also beneficial for https://github.com/cqfn/eo/issues/494 https://github.com/cqfn/eo/issues/485

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@andreoss seems to be a conflict with your own changes. Please, resync.

**Comment by andreoss** [comment]
@yegor256 Done

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@andreoss thanks!

**Pull request merged**
