### PR TITLE
(#431) - Reimplement atoms in EO for `float`

### PR DESCRIPTION
**Pull request by andreoss**
Per #431 
- Rename `empty` to `is-empty`
- Implement deducible atoms in EO for `float`

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#452](https://github.com/cqfn/eo/issues/452); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@andreoss still working on this or I can try to merge?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#452](https://github.com/cqfn/eo/issues/452); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#452](https://github.com/cqfn/eo/issues/452); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by andreoss** [comment]
> @andreoss still working on this or I can try to merge?
@yegor256 Yes. Part for `int` will be in the following PR.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@andreoss you have to turn off `SnippetTest` (by adding `@Disabled` to it) and also rename `eo-maven-plugin/src/it` to `it-disabled`. Otherwise we won't merge this.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@andreoss now something is wrong with one of the objects

**Comment by andreoss** [comment]
> @andreoss now something is wrong with one of the objects

@yegor256 Fixed.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#452` is not assigned, can't get performer

**Pull request merged**
