### PR TITLE
add saving array length in bitwise operations

### PR DESCRIPTION
**Pull request by IngeniariusSoftware**

### CODE REVIEW

**Comment by yegor256** [comment]
@IngeniariusSoftware I think that if two arrays are of different lengths, we must throw an exception

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#464](https://github.com/cqfn/eo/issues/464); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by IngeniariusSoftware** [comment]
@yegor256 we have another problem with bytes operation

ByteBuffer and BigInteger have diffrent system of storage number, for example number -25723423423423L

ByteBuffer: [-1, -1, -24, -102, -52, 124, 4, 65]

BigInteger: [-24, -102, -52, 124, 4, 65]

So if we do not know that we are working only with the int type it becomes a problem

**Comment by yegor256** [comment]
@IngeniariusSoftware I don't think we need to work with BigInteger at all. We should just convert `long` to 8 bytes and that's it.

**Comment by IngeniariusSoftware** [comment]
@yegor256 , what way do you intend to implement instead of BigInteger or do you suggest not working with bytes longer than 8?

**Comment by yegor256** [comment]
@IngeniariusSoftware I would work with byte arrays directly, using `for`. Basically, iterating through elements and applying AND/OR operations to them. In case of shifting left/right, I would also try to work with the array. The algorithm would be more complex, by still possible to implement.

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#464` is not assigned, can't get performer

**Pull request closed without merging**
